# This file loads the "config" module with values set by the ENV variables below
koop-provider-redshift-analytics:
  redshift:
    host: "KOOP_REDSHIFT_HOST"
    port: "KOOP_REDSHIFT_PORT"
    user: "KOOP_REDSHIFT_USER"
    password: "KOOP_REDSHIFT_PASSWORD"
    database: "KOOP_REDSHIFT_DATABASE"
    schema: "KOOP_REDSHIFT_SCHEMA"
    table: "KOOP_REDSHIFT_TABLE"
    eventColumn: "KOOP_REDSHIFT_EVENT_COLUMN"
    sessionColumn: "KOOP_REDSHIFT_SESSION_COLUMN"
    eventTimestampColumn: "KOOP_REDSHIFT_TIMESTAMP_COLUMN"
